-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 15:00:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizza_shoppe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza_shoppe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_shoppe` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizza_shoppe` ;

-- -----------------------------------------------------
-- Table `pizza_shoppe`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_shoppe`.`customers` ;

CREATE TABLE IF NOT EXISTS `pizza_shoppe`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_firstname` VARCHAR(100) NULL DEFAULT NULL,
  `customer_lastname` VARCHAR(100) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza_shoppe`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_shoppe`.`order_items` ;

CREATE TABLE IF NOT EXISTS `pizza_shoppe`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `line_item_total` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `pizza_id_idx` (`pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `pizza_shoppe`.`orders` (`order_id`),
  CONSTRAINT `fk_order_items_pizzas`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizza_shoppe`.`pizzas` (`pizza_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza_shoppe`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_shoppe`.`orders` ;

CREATE TABLE IF NOT EXISTS `pizza_shoppe`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `order_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_customer_order` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_order`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pizza_shoppe`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza_shoppe`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_shoppe`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `pizza_shoppe`.`pizzas` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `pizza_name` VARCHAR(100) NULL DEFAULT NULL,
  `pizza_price` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pizza_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `pizza_shoppe`;

DELIMITER $$

USE `pizza_shoppe`$$
DROP TRIGGER IF EXISTS `pizza_shoppe`.`Order_items_BEFORE_INSERT` $$
USE `pizza_shoppe`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza_shoppe`.`Order_items_BEFORE_INSERT`
BEFORE INSERT ON `pizza_shoppe`.`order_items`
FOR EACH ROW
BEGIN
DECLARE total_price DECIMAL(10,2);
    SELECT p.pizza_price * NEW.quantity INTO total_price
    FROM Pizzas p
    WHERE p.pizza_id = NEW.pizza_id;
    
    SET NEW.line_item_total = total_price;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Total Money Spent by Each Customer--
SELECT
  c.customer_id,
  CONCAT(c.customer_firstname, ' ', c.customer_lastname) AS customer_name,
  SUM(oi.quantity * p.pizza_price) AS total_spent
FROM
  Customers c
JOIN
  Orders o ON c.customer_id = o.customer_id
JOIN
  Order_Items oi ON o.order_id = oi.order_id
JOIN
  Pizzas p ON oi.pizza_id = p.pizza_id
GROUP BY
  c.customer_id;
-- Total Money Spent by Each Customer by Date--
SELECT
  c.customer_id,
  CONCAT(c.customer_firstname, ' ', c.customer_lastname) AS customer_name,
  DATE(o.order_datetime) AS order_date,
  SUM(oi.quantity * p.pizza_price) AS total_spent
FROM
  Customers c
JOIN
  Orders o ON c.customer_id = o.customer_id
JOIN
  Order_Items oi ON o.order_id = oi.order_id
JOIN
  Pizzas p ON oi.pizza_id = p.pizza_id
GROUP BY
  c.customer_id, DATE(o.order_datetime);
